In [2]:
import pandas as pd 
import string 
from pprint import pprint 
from time import time
from nltk.corpus import stopwords

In [3]:
Spam_Collection=pd.read_csv(r"C:\Users\Eswar\Desktop\Simpli_Learn\Data Science With Python\MessageSpamCollection_dataset\SpamCollection\SpamCollection",sep='\t',header=None,names=['response', 'message'])


In [4]:
Spam_Collection.head()

response                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
Spam_Collection.shape

(5572, 2)

In [6]:
Spam_Collection.describe()

response                 message
count      5572                    5572
unique        2                    5169
top         ham  Sorry, I'll call later
freq       4825                      30

In [7]:
Spam_Collection.groupby('response').describe()


message                                                            \
           count unique                                                top   
response                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    653  Please call our customer service representativ...   

               
         freq  
response       
ham        30  
spam        4

In [8]:
len

<function len(obj, /)>

In [9]:
len(Spam_Collection.message)

5572

In [10]:
Spam_Collection['length'] = Spam_Collection['message'].apply(len)

In [11]:
Spam_Collection.head()

response                                            message  length
0      ham  Go until jurong point, crazy.. Available only ...     111
1      ham                      Ok lar... Joking wif u oni...      29
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     155
3      ham  U dun say so early hor... U c already then say...      49
4      ham  Nah I don't think he goes to usf, he lives aro...      61

In [12]:
max(Spam_Collection.length)

910

In [13]:
min(Spam_Collection.length)

2

In [14]:
Spam_Collection.columns

Index(['response', 'message', 'length'], dtype='object')

In [15]:
from sklearn.model_selection import train_test_split
Z=Spam_Collection.drop("response",1)
X=Z.drop("length",1)
Y=Spam_Collection.response


In [16]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.25, random_state=1) 


In [17]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)



(4179, 1)
(1393, 1)
(4179,)
(1393,)


In [18]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [19]:
No_Punctuation= [char for char in Spam_Collection.message[0] if char not in string.punctuation]

In [20]:
No_Punctuation

['G',
 'o',
 ' ',
 'u',
 'n',
 't',
 'i',
 'l',
 ' ',
 'j',
 'u',
 'r',
 'o',
 'n',
 'g',
 ' ',
 'p',
 'o',
 'i',
 'n',
 't',
 ' ',
 'c',
 'r',
 'a',
 'z',
 'y',
 ' ',
 'A',
 'v',
 'a',
 'i',
 'l',
 'a',
 'b',
 'l',
 'e',
 ' ',
 'o',
 'n',
 'l',
 'y',
 ' ',
 'i',
 'n',
 ' ',
 'b',
 'u',
 'g',
 'i',
 's',
 ' ',
 'n',
 ' ',
 'g',
 'r',
 'e',
 'a',
 't',
 ' ',
 'w',
 'o',
 'r',
 'l',
 'd',
 ' ',
 'l',
 'a',
 ' ',
 'e',
 ' ',
 'b',
 'u',
 'f',
 'f',
 'e',
 't',
 ' ',
 'C',
 'i',
 'n',
 'e',
 ' ',
 't',
 'h',
 'e',
 'r',
 'e',
 ' ',
 'g',
 'o',
 't',
 ' ',
 'a',
 'm',
 'o',
 'r',
 'e',
 ' ',
 'w',
 'a',
 't']

In [21]:
No_Punctuation_Msg=''.join(No_Punctuation)

In [22]:
No_Punctuation_Msg

'Go until jurong point crazy Available only in bugis n great world la e buffet Cine there got amore wat'

In [23]:
Spam_Collection.message[0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [24]:
No_Punctuation_Msg.split()

['Go',
 'until',
 'jurong',
 'point',
 'crazy',
 'Available',
 'only',
 'in',
 'bugis',
 'n',
 'great',
 'world',
 'la',
 'e',
 'buffet',
 'Cine',
 'there',
 'got',
 'amore',
 'wat']

In [25]:
import nltk

In [26]:
import string
from nltk.corpus import stopwords

In [27]:
a=stopwords.words("english")[0:10]
a

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]

In [28]:
Clean_Sentence=[ word for word in No_Punctuation_Msg.split() if word.lower() in stopwords.words("english")]
Clean_Sentence

['until', 'only', 'in', 'there']

In [29]:
stopwords_json = pd.read_json("https://raw.githubusercontent.com/6/stopwords-json/master/dist/en.json" )
stopwords_json.head(3)
stopwords_json.columns = ["en"]
x = stopwords.words("english")

In [30]:
stopwords_json_en = set(stopwords_json['en'])
stopwords_nltk_en = set(x)
stoplist_combined = set.union(stopwords_json_en, stopwords_nltk_en)

In [31]:
def cleanup_text(msg):
    No_Punctuation = [char for char in msg if char not in string.punctuation]
    No_Punctuation_Msg = ''.join(No_Punctuation) #joins all the strings
    return [word.lower() for word in No_Punctuation_Msg.split() if word.lower() not in stoplist_combined]

In [32]:
#Cleaned['message'] = X_train['message'].head().apply(cleanup_text)
#Cleaned.message

In [33]:
X_train.message

710     4mths half price Orange line rental & latest c...
3740                           Did you stitch his trouser
2711    Hope you enjoyed your new content. text stop t...
3155    Not heard from U4 a while. Call 4 rude chat pr...
3748    Ü neva tell me how i noe... I'm not at home in...
                              ...                        
905     We're all getting worried over here, derek and...
5192    Oh oh... Den muz change plan liao... Go back h...
3980    CERI U REBEL! SWEET DREAMZ ME LITTLE BUDDY!! C...
235     Text & meet someone sexy today. U can find a d...
5157                              K k:) sms chat with me.
Name: message, Length: 4179, dtype: object

In [34]:
#Clean['message'] = X_test['message'].head().apply(cleanup_text)
#Clean.message

In [35]:
import sklearn
from sklearn.feature_extraction.text import CountVectorizer

In [36]:
import re

In [37]:
def stemming_tokenizer(str_input):
    words = re.sub(r"[^A-Za-z0-9\-]", " ", str_input).lower().split()
    words = [porter_stemmer.stem(word) for word in words]
    return words

In [38]:
bag_of_words_tfrmr = CountVectorizer(analyzer= cleanup_text).fit(X_train['message'])
print(bag_of_words_tfrmr)

CountVectorizer(analyzer=<function cleanup_text at 0x000002B58A1E5678>,
                binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)


In [39]:
d = bag_of_words_tfrmr.vocabulary_
list(d.items())

[('4mths', 527),
 ('half', 3260),
 ('price', 5369),
 ('orange', 4959),
 ('line', 4112),
 ('rental', 5658),
 ('latest', 4022),
 ('camera', 1607),
 ('phones', 5161),
 ('4', 481),
 ('free', 2925),
 ('phone', 5157),
 ('11mths', 265),
 ('call', 1575),
 ('mobilesdirect', 4534),
 ('08000938767', 46),
 ('update', 7096),
 ('or2stoptxt', 4957),
 ('tcs', 6660),
 ('stitch', 6413),
 ('trouser', 6969),
 ('hope', 3456),
 ('enjoyed', 2575),
 ('content', 1961),
 ('text', 6718),
 ('stop', 6423),
 ('61610', 583),
 ('unsubscribe', 7089),
 ('help08712400602450p', 3355),
 ('provided', 5436),
 ('tones2youcouk', 6891),
 ('heard', 3328),
 ('u4', 7032),
 ('rude', 5801),
 ('chat', 1730),
 ('private', 5383),
 ('01223585334', 4),
 ('cum', 2085),
 ('wan', 7282),
 ('2c', 388),
 ('pics', 5175),
 ('gettin', 3071),
 ('shagged', 5986),
 ('pix', 5197),
 ('8552', 688),
 ('2end', 393),
 ('send', 5947),
 ('sam', 5846),
 ('xxx', 7611),
 ('ü', 7760),
 ('neva', 4725),
 ('noe', 4780),
 ('im', 3586),
 ('home', 3437),
 ('da', 211

In [40]:
#bag_of_words_tfrmr_1 = CountVectorizer(analyzer= cleanup_text).fit(Cleaned['message'])
#print(bag_of_words_tfrmr)

In [41]:
#e = bag_of_words_tfrmr_1.vocabulary_
#list(e.items())

In [42]:
{k: d[k] for k in list(d.keys())[:20]}

{'4mths': 527,
 'half': 3260,
 'price': 5369,
 'orange': 4959,
 'line': 4112,
 'rental': 5658,
 'latest': 4022,
 'camera': 1607,
 'phones': 5161,
 '4': 481,
 'free': 2925,
 'phone': 5157,
 '11mths': 265,
 'call': 1575,
 'mobilesdirect': 4534,
 '08000938767': 46,
 'update': 7096,
 'or2stoptxt': 4957,
 'tcs': 6660,
 'stitch': 6413}

In [43]:
msg_bagofwords = bag_of_words_tfrmr.transform(X_train['message'])

In [44]:
print(msg_bagofwords.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [45]:
msg_bagofwords.shape

(4179, 7767)

In [46]:
bag_of_words_tfrmr=CountVectorizer(analyzer=cleanup_text, binary=True).fit(X_train['message'])

In [47]:
bow = bag_of_words_tfrmr.transform(X_train['message'])

In [48]:
print(bow.shape)

(4179, 7767)


In [49]:
print([bow[3,i] for i in range(bow.shape[1]) if bow[3,i]!=0])

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [50]:
from sklearn.feature_extraction.text import TfidfTransformer


In [51]:

tfidf_transformer = TfidfTransformer().fit(msg_bagofwords)
print(tfidf_transformer)

TfidfTransformer(norm='l2', smooth_idf=True, sublinear_tf=False, use_idf=True)


In [52]:
msg_tfidf = tfidf_transformer.transform(msg_bagofwords)
print(msg_tfidf.shape)

(4179, 7767)


In [53]:
[msg_tfidf[0,i] for i in range(msg_tfidf.shape[1]) if msg_tfidf[0,i]!=0]

[0.27680346298888897,
 0.2526748114162265,
 0.13942729995788955,
 0.27680346298888897,
 0.11658330656564357,
 0.2103317423273042,
 0.2946426881094261,
 0.2033463380330262,
 0.21164549393688367,
 0.20031744711761582,
 0.27680346298888897,
 0.27680346298888897,
 0.21591331582916273,
 0.16510333009738964,
 0.23856045505325238,
 0.21908006944345038,
 0.2449071205832383,
 0.21746069439600033,
 0.23079276422026418]

In [54]:
from sklearn.naive_bayes import MultinomialNB

In [55]:
X_train = msg_tfidf

In [56]:
 Spam_Classification_model=MultinomialNB().fit(X_train , Y_train)

In [57]:
Spam_Classification_model

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [58]:
Spam_Classification_model.score(X_train,Y_train)

0.9767887054319215

In [59]:
X_test.shape

(1393, 1)

In [60]:
bow_test = bag_of_words_tfrmr.transform(X_test['message'])

In [61]:
bow_test.shape

(1393, 7767)

In [62]:
print([bow_test[3,i] for i in range(bow_test.shape[1]) if bow_test[3,i]!=0])

[1]


In [63]:
print(bow_test)

  (0, 5365)	1
  (0, 7645)	1
  (1, 4310)	1
  (1, 4529)	1
  (1, 5377)	1
  (2, 1009)	1
  (2, 7368)	1
  (3, 3311)	1
  (4, 342)	1
  (4, 1629)	1
  (4, 2111)	1
  (4, 2892)	1
  (4, 4062)	1
  (4, 5354)	1
  (4, 6086)	1
  (4, 6193)	1
  (4, 7537)	1
  (4, 7760)	1
  (5, 342)	1
  (5, 6780)	1
  (5, 7282)	1
  (5, 7304)	1
  (6, 342)	1
  (6, 1546)	1
  (6, 4343)	1
  :	:
  (1389, 3456)	1
  (1390, 2983)	1
  (1390, 4199)	1
  (1390, 4448)	1
  (1390, 4502)	1
  (1390, 4846)	1
  (1390, 5949)	1
  (1390, 5956)	1
  (1390, 6718)	1
  (1391, 2649)	1
  (1391, 3700)	1
  (1391, 4532)	1
  (1391, 4603)	1
  (1391, 7113)	1
  (1391, 7217)	1
  (1391, 7427)	1
  (1391, 7436)	1
  (1392, 882)	1
  (1392, 2477)	1
  (1392, 2940)	1
  (1392, 3236)	1
  (1392, 4400)	1
  (1392, 4652)	1
  (1392, 5749)	1
  (1392, 7282)	1


In [64]:
X_test_tfidf= tfidf_transformer.transform(bow_test)

In [65]:
print(X_test_tfidf)

  (0, 7645)	0.7255411999351792
  (0, 5365)	0.6881787320141625
  (1, 5377)	0.5537358664799058
  (1, 4529)	0.6993766122230567
  (1, 4310)	0.4519390937384682
  (2, 7368)	0.7359969143596613
  (2, 1009)	0.6769848905648173
  (3, 3311)	1.0
  (4, 7760)	0.23397662078330114
  (4, 7537)	0.3574167338680539
  (4, 6193)	0.3473726711264934
  (4, 6086)	0.36999564021857745
  (4, 5354)	0.3868369046973467
  (4, 4062)	0.32558392907734063
  (4, 2892)	0.3083238130839835
  (4, 2111)	0.2410665781758287
  (4, 1629)	0.3430175373203306
  (4, 342)	0.1829160665578414
  (5, 7304)	0.49535444859671707
  (5, 7282)	0.5568759985881109
  (5, 6780)	0.5620422698800048
  (5, 342)	0.3586385078600294
  (6, 6992)	0.6268655397617149
  (6, 4343)	0.5722223643169534
  (6, 1546)	0.44339823650845817
  :	:
  (1389, 2161)	0.520578412556378
  (1390, 6718)	0.21975511604806672
  (1390, 5956)	0.42422006489143427
  (1390, 5949)	0.42422006489143427
  (1390, 4846)	0.2565067320482406
  (1390, 4502)	0.32534554032772883
  (1390, 4448)	0.4242200

In [66]:
X_test_tfidf.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [67]:
y_pred_class = Spam_Classification_model.predict(X_test_tfidf)
df = pd.DataFrame({"predicted": y_pred_class, "actual": Y_test})

In [68]:
df

predicted actual
1078       ham    ham
4028       ham    ham
958        ham    ham
4642       ham    ham
4674       ham    ham
...        ...    ...
3207       ham    ham
4655       ham    ham
1140       ham    ham
1793      spam   spam
1710       ham    ham

[1393 rows x 2 columns]

In [69]:
from sklearn.metrics import accuracy_score

In [70]:
accuracy_score(Y_test,y_pred_class)

0.964824120603015

In [71]:
pd.crosstab(Y_test,y_pred_class)

col_0      ham  spam
response            
ham       1208     0
spam        49   136

In [72]:
Spam_Classification_model.predict_proba(X_test_tfidf)

array([[0.97253909, 0.02746091],
       [0.97643542, 0.02356458],
       [0.90199174, 0.09800826],
       ...,
       [0.93247434, 0.06752566],
       [0.40723912, 0.59276088],
       [0.99598244, 0.00401756]])

In [73]:
Y_predict_proba = Spam_Classification_model.predict_proba(X_test_tfidf)[:,1]

In [74]:
Y_predict_proba

array([0.02746091, 0.02356458, 0.09800826, ..., 0.06752566, 0.59276088,
       0.00401756])

In [75]:
print(Y_predict_proba.shape)
print(Y_test.shape)

(1393,)
(1393,)


In [76]:
from sklearn import metrics

In [77]:
metrics.roc_auc_score( Y_test,Y_predict_proba)

0.9856855199570432

In [78]:
X_test_tfidf.shape

(1393, 7767)

In [79]:
y_pred_class[0]

'ham'

In [80]:
y_pred_class = Spam_Classification_model.predict(X_test_tfidf)
y_pred_class

array(['ham', 'ham', 'ham', ..., 'ham', 'spam', 'ham'], dtype='<U4')

In [87]:
mail = " i need some notes "

In [88]:
message_bagofwords = bag_of_words_tfrmr.transform([mail])

In [89]:
from sklearn.feature_extraction.text import TfidfTransformer

In [90]:
Tfidf_transformer = TfidfTransformer().fit(message_bagofwords)

In [91]:
message_tfidf=tfidf_transformer.transform(message_bagofwords)
message_tfidf.shape

(1, 7767)

In [92]:
print('predicted',Spam_Classification_model.predict(message_tfidf))

predicted ['ham']
